### ISSUE TITLE
Release needed

### ISSUE THREAD

**Issue by dzuelke** [alrik11es/cowsayphp#2]
The docs say `\Cowsay\Cow`, but that needs `dev-master`, which the docs don't mention - a simple `composer require` will install version 1.0.0 of the library, with class `\League\Cowsay\Cow`.

Can you please tag a new release?

**Comment by alrik11es** [comment]
Sorry for the delay. I will take a look to your request as soon as I can.

**Comment by alrik11es** [comment]
New release has been added to the project. Thanks for your feedback.
