### ISSUE TITLE
I have a request.

### ISSUE THREAD

**Issue by chell-uoxou** [alrik11es/cowsayphp#4]
Nice to meet you.
I am developing a console system using PHP.
Well, I want to include your cowsayphp to it.
I will appear in the sight of the author.

Please reply.
chell rui

**Comment by alrik11es** [comment]
Hello @chell-uoxou you can use cowsayphp as you want. It's free to use, commercially or whatever, MIT licensed.

Is your program going to be an open source app?

**Comment by chell-uoxou** [comment]
Thank you! ! Forever mine is an open source.

**Comment by chell-uoxou** [comment]
Your project is very nice!

**Comment by alrik11es** [comment]
You're welcome. I'll keep looking to update this little project.
