### ISSUE TITLE
Can't install from Composer

### ISSUE THREAD

**Issue by BenMJimenez** [alrik11es/cowsayphp#5]
When I try to run  composer require alriklles/cowsayphp in a headless Ubuntu server 16.04 I get this message. 

[invalidargumentexception]
Could not find package alriklles/cowsayphp at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

Is there a way to fix this?

**Comment by BenMJimenez** [comment]
I figured out the issue. It seems it's not alriklles, it's alrik11es. Ones not L's

**Comment by alrik11es** [comment]
Thats It, thanks for trying out :+1:
